var tree = [["[Global Namespace]",,"",
                [["Achievement","Achievement.html"," < Eloquent",
                [        ]],["Admin","Admin.html"," < Eloquent",
                [        ]],["Answer","Answer.html"," < Eloquent",
                [        ]],["BaseController","BaseController.html"," < Controller",
                [        ]],["Challenge","Challenge.html"," < Eloquent",
                [        ]],["Chapter","Chapter.html"," < Eloquent",
                [        ]],["Course","Course.html"," < Eloquent",
                [        ]],["DatabaseSeeder","DatabaseSeeder.html"," < Seeder",
                [        ]],["HomeController","HomeController.html"," < BaseController",
                [        ]],["Option","Option.html"," < Eloquent",
                [        ]],["Organization","Organization.html"," < Eloquent",
                [        ]],["Question","Question.html"," < Eloquent",
                [        ]],["Quiz","Quiz.html"," < Eloquent",
                [        ]],["QuizQuestion","QuizQuestion.html"," < Eloquent",
                [        ]],["Stat","Stat.html"," < Eloquent",
                [        ]],["Student","Student.html"," < Eloquent",
                [        ]],["Subject","Subject.html"," < Eloquent",
                [        ]],["Teacher","Teacher.html"," < Eloquent",
                [        ]],["User","User.html"," < Ardent",
                [        ]],["UsersController","UsersController.html"," < BaseController",
                [        ]]        ]]        ]

